/*
** EPITECH PROJECT, 2022
** Project
** File description:
** Description
*/

#pragma once

#define BLINKY_GHOST_LEFT 8
#define BLINKY_GHOST_RIGHT 9
#define BLINKY_GHOST_FRONTFACING 18
#define BLINKY_GHOST_BACKFACING 19

#define INKY_GHOST_LEFT 30
#define INKY_GHOST_RIGHT 31
#define INKY_GHOST_FRONTFACING 40
#define INKY_GHOST_BACKFACING 41

#define PINKY_GHOST_LEFT 32
#define PINKY_GHOST_RIGHT 33
#define PINKY_GHOST_FRONTFACING 42
#define PINKY_GHOST_BACKFACING 43

#define CLYDE_GHOST_LEFT 34
#define CLYDE_GHOST_RIGHT 35
#define CLYDE_GHOST_FRONTFACING 44
#define CLYDE_GHOST_BACKFACING 45

#define GHOST_HUNTED 36
#define GHOST_DEFEATED 29

#define PACMAN_HEAD 28

#define PACGUM 25
#define BASICALLY_COCAINE 26

#define TERRAIN_FLOOR 11


#define BASIC 0
#define BLINKY 1
#define PINKY 2
#define INKY 3
#define CLYDE 4

#define CONFIG_PATH "./assets/pacman/graphics_cfg.csv"
