/*
** EPITECH PROJECT, 2022
** CoreMacros.hpp
** File description:
** .
*/

#pragma once

#define PIPE_MIDDLE_LEFT 0
#define PIPE_MIDDLE_RIGHT 1
#define PIPE_UPPER_LEFT 2
#define PIPE_UPPER_RIGHT 3
#define PIPE_LOWER_LEFT 4
#define PIPE_LOWER_RIGHT 5
#define SKY 6
#define TRUNK 7
#define FENCE 8
#define SMALL_CLOUD 9
#define CLOUD_UPPER_LEFT 10
#define CLOUD_UPPER_MIDDLE 11
#define CLOUD_UPPER_RIGHT 12
#define CLOUD_LOWER_LEFT 13
#define CLOUD_LOWER_MIDDLE 14
#define CLOUD_LOWER_RIGHT 15
#define G_CUBE 16
#define QUESTION_CUBE 17
#define FLOOR 18
#define TOP_POLE 19
#define POLE 20
#define SHROOM_LEFT 21
#define SHROOM_MIDDLE 22
#define SHROOM_RIGHT 23
#define ARCADE_UPPER_1 30
#define ARCADE_UPPER_2 31
#define ARCADE_UPPER_3 32
#define ARCADE_UPPER_4 33
#define ARCADE_UPPER_5 34
#define ARCADE_UPPER_6 35
#define ARCADE_UPPER_7 36
#define ARCADE_UPPER_8 37
#define ARCADE_LOWER_1 40
#define ARCADE_LOWER_2 41
#define ARCADE_LOWER_3 42
#define ARCADE_LOWER_4 43
#define ARCADE_LOWER_5 44
#define ARCADE_LOWER_6 45
#define ARCADE_LOWER_7 46
#define ARCADE_LOWER_8 47