/*
** EPITECH PROJECT, 2022
** CoreMacros.hpp
** File description:
** .
*/

#pragma once

// Tiles (NOT UPDATED)
// AS THESE VALUES ARE NOT CURRENTLY USED, THEY ARE NOT UPDATED
#define PIPE_MIDDLE_LEFT 0
#define PIPE_MIDDLE_RIGHT 1
#define PIPE_UPPER_LEFT 2
#define PIPE_UPPER_RIGHT 3
#define PIPE_LOWER_LEFT 4
#define PIPE_LOWER_RIGHT 5
#define SKY 6
#define TRUNK 7
#define FENCE 8
#define SMALL_CLOUD 9
#define CLOUD_UPPER_LEFT 10
#define CLOUD_UPPER_MIDDLE 11
#define CLOUD_UPPER_RIGHT 12
#define CLOUD_LOWER_LEFT 13
#define CLOUD_LOWER_MIDDLE 14
#define CLOUD_LOWER_RIGHT 15
#define GAME_UNSELECTED 16
#define GAME_SELECTED 65
#define QUESTION_CUBE 17